name: Build

on:
  push:
    branches: [ "master","ankokusamochi", "main" ]
  pull_request:
    branches: [ "master","ankokusamochi", "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild.exe path
        run: |
          sudo apt-get install -y apt-transport-https
          sudo apt-get update
          sudo apt-get install -y mono-devel
          sudo apt-get install -y msbuild
          echo "msbuild: $(which msbuild)"
        
      - name: Build
        run: |
          msbuild /p:Configuration=Release /p:TargetFrameworkVersion=v3.5

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: COM3D2.InOutAnimation
          path: /home/runner/work/COM3D2.InOutAnimation/COM3D2.InOutAnimation/InOutAnimation/bin/Release/COM3D2.InOutAnimation.Plugin.dll
    
